# Configuration
SRL_MAX_TEXTURES = 1            # Number of VDP1 texture slots
SRL_MODE = NTSC                 # Valid options are PAL or NTSC
SRL_HIGH_RES = 0                # 480i mode
SRL_FRAMERATE = 1               # Framerate control (0=dynamic, 1=< 60/value)
SRL_MAX_CD_BACKGROUND_JOBS = 1  # Maximum number of files GFS can open at once
SRL_MAX_CD_FILES = 256          # Maximum number of files on a CD
SRL_MAX_CD_RETRIES = 3          # Number of times to retry on unsuccessful read
SRL_LOG_LEVEL = TESTING         # Maximum log level to display
SRL_LOG_OUTPUT ?= EMULATOR    	# Log output method (DEV_CART, EMULATOR, NONE)
SRL_MALLOC_METHOD = SIMPLE

# Increase Log output buffer to avoid overflow
SRL_DEBUG_MAX_LOG_LENGTH = 255

# Sound driver specific configuration
SRL_USE_SGL_SOUND_DRIVER = 0    # Set to 1 if you want to use SGL sound driver
SRL_ENABLE_FREQ_ANALYSIS = 0    # Set to 1 if you want to enable frequency analysis

# SGL configuration
SGL_MAX_VERTICES = 2500         # Number of vertices that can be used
SGL_MAX_POLYGONS = 1500         # Number of polygons that can be used
SGL_MAX_EVENTS = 1             	# Number of events that can be used
SGL_MAX_WORKS = 1             	# Number of works that can be used

# Disk name
CD_NAME = HostIOUTs

# Directory build will be placed into
BUILD_DROP = ./BuildDrop

# SRL installation directory
SRL_INSTALL_ROOT ?= ../../..

# Include HostIO extra module
MODULES_EXTRA = SRL_HostIO

# Custom FLAGS: include main Tests/src/ folder to access minunit.h and display.hpp
SRL_CUSTOM_CCFLAGS = -DNO_SGL_STDLIB -Wno-attribute-warning -I$(SRL_INSTALL_ROOT)/Tests/src
SRL_CUSTOM_LDFLAGS = -lstdc++

# Find all .c and .cxx files
SOURCES = $(patsubst ./%,%,$(shell find src/ -name '*.c')) 
SOURCES += $(patsubst ./%,%,$(shell find src/ -name '*.cxx'))

# Include shared makefile
SDK_ROOT = $(SRL_INSTALL_ROOT)/saturnringlib
include $(SDK_ROOT)/shared.mk
